# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-16 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0002_auto_20160316_2239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='province',
            name='nr',
        ),
        migrations.AddField(
            model_name='province',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
