# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-16 23:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0003_auto_20160316_2242'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=42)),
                ('num_of_inhabitants', models.BigIntegerField(default=0)),
                ('num_of_entitled_inhabitants', models.BigIntegerField(default=0)),
                ('num_of_distributed_ballots', models.BigIntegerField(default=0)),
                ('num_of_votes', models.BigIntegerField(default=0)),
                ('num_of_valid_votes', models.BigIntegerField(default=0)),
                ('name_of_province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_site.Province')),
            ],
        ),
    ]
