# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-16 23:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0004_commune'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commune',
            old_name='name_of_province',
            new_name='province',
        ),
    ]
