# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-01 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0005_auto_20160316_2325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='province',
            name='num_of_distributed_ballots',
        ),
        migrations.RemoveField(
            model_name='province',
            name='num_of_entitled_inhabitants',
        ),
        migrations.RemoveField(
            model_name='province',
            name='num_of_inhabitants',
        ),
        migrations.RemoveField(
            model_name='province',
            name='num_of_valid_votes',
        ),
        migrations.RemoveField(
            model_name='province',
            name='num_of_votes',
        ),
        migrations.AlterField(
            model_name='commune',
            name='num_of_distributed_ballots',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='commune',
            name='num_of_entitled_inhabitants',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='commune',
            name='num_of_inhabitants',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='commune',
            name='num_of_valid_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='commune',
            name='num_of_votes',
            field=models.IntegerField(default=0),
        ),
    ]
