# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-02 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0006_auto_20160401_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commune',
            name='num_of_distributed_ballots',
        ),
        migrations.RemoveField(
            model_name='commune',
            name='num_of_entitled_inhabitants',
        ),
        migrations.RemoveField(
            model_name='commune',
            name='num_of_inhabitants',
        ),
        migrations.RemoveField(
            model_name='commune',
            name='num_of_valid_votes',
        ),
        migrations.RemoveField(
            model_name='commune',
            name='num_of_votes',
        ),
        migrations.AddField(
            model_name='commune',
            name='distributed_ballots',
            field=models.IntegerField(default=0, verbose_name='Distributed ballots'),
        ),
        migrations.AddField(
            model_name='commune',
            name='entitled_inhabitants',
            field=models.IntegerField(default=0, verbose_name='Entitled inhabitants'),
        ),
        migrations.AddField(
            model_name='commune',
            name='inhabitants',
            field=models.IntegerField(default=0, verbose_name='Inhabitants'),
        ),
        migrations.AddField(
            model_name='commune',
            name='valid_votes',
            field=models.IntegerField(default=0, verbose_name='Valid votes'),
        ),
        migrations.AddField(
            model_name='commune',
            name='votes',
            field=models.IntegerField(default=0, verbose_name='Votes'),
        ),
    ]
