# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-05 14:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0008_candidate_voting'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommuneType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=42)),
            ],
        ),
        migrations.AlterField(
            model_name='commune',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_site.Province', verbose_name='Province'),
        ),
        migrations.AddField(
            model_name='commune',
            name='type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main_site.CommuneType', verbose_name='Commune type'),
            preserve_default=False,
        ),
    ]
