# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-07 13:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0010_inhabitantsrange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inhabitantsrange',
            name='begin',
            field=models.IntegerField(default=0, verbose_name='Begin'),
        ),
        migrations.AlterField(
            model_name='inhabitantsrange',
            name='end',
            field=models.IntegerField(default=0, verbose_name='End'),
        ),
        migrations.AlterField(
            model_name='inhabitantsrange',
            name='name',
            field=models.CharField(max_length=42, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='voting',
            name='candidate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_site.Candidate'),
        ),
        migrations.AlterField(
            model_name='voting',
            name='commune',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_site.Commune'),
        ),
        migrations.AlterField(
            model_name='voting',
            name='votes',
            field=models.IntegerField(default=0, verbose_name='Votes'),
        ),
    ]
