# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-07 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0014_auto_20160407_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='province',
            name='name',
            field=models.CharField(blank=True, max_length=42, null=True),
        ),
    ]
