# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-06-04 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0015_auto_20160407_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='commune',
            name='last_mod_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
