# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-06-04 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0016_commune_last_mod_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='commune',
            name='last_mod_user',
            field=models.CharField(default='admin', max_length=42),
        ),
    ]
